### ISSUE TITLE
Include ARM builds

### ISSUE THREAD

**Issue by tommitytom** [akornatskyy/docker-library#20]
Thanks for making these images, they are great!  I had to build the ARM build locally on a Raspberry Pi - however I notice you use travis, and [their docs state](https://docs.travis-ci.com/user/multi-cpu-architectures/) you can build for multiple platforms relatively easily (though I'm unsure what has to happen on the docker side).  Would be nice to be able to pull them straight in from docker hub!

**Comment by akornatskyy** [comment]
added multi arch build for `linux/amd64` and `linux/arm64`. images pushed.
